# Generated by Django 3.2.7 on 2021-10-25 19:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('doubts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doubt',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='DoubtAnswers',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doubtq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='doubts.doubt')),
            ],
        ),
    ]
