# Generated by Django 3.2.7 on 2021-10-26 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doubts', '0002_auto_20211026_0030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doubtanswers',
            old_name='doubtq',
            new_name='question',
        ),
    ]
