# Generated by Django 3.2.7 on 2021-10-26 14:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doubts', '0004_auto_20211026_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='doubtanswers',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='auth.user'),
            preserve_default=False,
        ),
    ]
