# Generated by Django 3.2.7 on 2021-09-19 09:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0003_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_preview', models.BooleanField(default=False)),
                ('chapter_type', models.CharField(choices=[('T', 'TEXT'), ('H', 'HEADING'), ('V', 'VIDEO'), ('L', 'LINK')], max_length=2)),
                ('index', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='courses.course')),
                ('parent_chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_chapters', to='chapters.chapter')),
            ],
        ),
    ]
