# Generated by Django 3.2.7 on 2021-09-08 17:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('instructor', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('tagline', models.CharField(max_length=100, null=True)),
                ('price', models.IntegerField()),
                ('active', models.BooleanField(default=False)),
                ('discount', models.IntegerField(default=0)),
                ('duration', models.IntegerField()),
                ('thumbnail', models.ImageField(upload_to='media/thumbnails')),
                ('resource', models.FileField(upload_to='media/resource')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='courses.category')),
            ],
        ),
    ]
